#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import make_eboot as psp_builders

psp_sources = [
    "display_server_psp.cpp",
    "godot_psp.cpp",
    "ip_psp.cpp",
    "os_psp.cpp",
    "rasterizer_psp.cpp",
    "rasterizer_scene_psp.cpp",
    "texture_cache_psp.cpp",
]

program = env.add_program("#bin/godot", psp_sources)

if env["psp_build_eboot"]:
    eboot = env.Command(
        "#bin/EBOOT.PBP",
        program,
        env.Run(psp_builders.make_eboot, "Packing PSP EBOOT.PBP"),
    )
    env.Alias("eboot", eboot)
